In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np


In [3]:
a1=[1,2,3,4,5]

In [4]:
a=np.array(a1)

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
a.dtype

dtype('int64')

In [8]:
type(a),type(a1)

(numpy.ndarray, list)

In [9]:
a1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
a*2

array([ 2,  4,  6,  8, 10])

In [14]:
a1*a1

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
a*a

array([ 1,  4,  9, 16, 25])

In [16]:
a[0]

1

In [17]:
a[3]

4

In [21]:
a=np.append(a,66)

In [22]:
a=np.append(a,67)

array([ 1,  2,  3,  4,  5, 66, 67])

In [24]:
a2=np.array(a,dtype=float)

In [25]:
a2

array([ 1.,  2.,  3.,  4.,  5., 66.])

In [26]:
type(a2)

numpy.ndarray

In [27]:
a3=np.array(a,dtype=str)

In [28]:
a3

array(['1', '2', '3', '4', '5', '66'], dtype='<U21')

In [29]:
a4=[[1,2,3],[4,5,6]]

In [30]:
a4=np.array(a4)

In [31]:
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
len(a4)#its counting 1 array as 1

2

In [33]:
len(a3)

6

In [34]:
len(a1)

5

In [39]:
a2.ndim

1

In [40]:
a4.ndim

2

In [41]:
a.shape

(6,)

In [42]:
a4.shape

(2, 3)

In [43]:
a5=np.array([[1,2,3]])
a5.shape

(1, 3)

In [45]:
a.dtype

dtype('int64')

In [47]:
a3.dtype

dtype('<U21')

In [49]:
b=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
b=np.array(b)

In [50]:
b[0][0]

1

In [51]:
b[1][0]

6

In [52]:
b[1][2]

8

In [53]:
b[1]

array([ 6,  7,  8,  9, 10])

In [58]:
b[1][1:4]  #using cut in arrays , it include first but exclude last

array([7, 8, 9])

In [60]:
b[:,2] # first is for row and second one is for column

array([ 3,  8, 13])

In [64]:
b[0:3, 2]

array([ 3,  8, 13])

In [65]:
b[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [66]:
b[0:2,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [68]:
b[2][3]=1888

In [69]:
b[2][3]

1888

In [70]:
b[0:2,2:5]=345

In [71]:
b

array([[   1,    2,  345,  345,  345],
       [   6,    7,  345,  345,  345],
       [  11,   12,   13, 1888,   15]])

In [73]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((3,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [75]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.ones((3,3),dtype='str')

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [78]:
np.full((3,3),69,dtype='int32')

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]], dtype=int32)

In [79]:
np.full((3,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
np.random.rand(4,4)

array([[0.35410591, 0.48997068, 0.81392799, 0.91652102],
       [0.21508824, 0.11503001, 0.74082866, 0.69502486],
       [0.36479603, 0.93598809, 0.79422742, 0.87926854],
       [0.33581189, 0.77806879, 0.60150225, 0.28032762]])

In [81]:
np.random.randint(-4,2, size=(3,3))

array([[ 1, -3,  0],
       [-2, -2, -1],
       [ 1, -1,  1]])

In [83]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
c=np.random.randint(1,5 ,size=(1,5))
c

array([[3, 3, 3, 2, 2]])

In [89]:
c+2

array([[5, 5, 5, 4, 4]])

In [91]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [93]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [96]:
np.reshape(arr,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

In [98]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
np.concatenate((arr,arr), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [102]:
np.concatenate((arr,arr), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [103]:
np.split(arr,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [105]:
brr = np.array([[1, 2, 3,66], [4, 5, 6,67]])
np.split(brr,2,axis=1)

[array([[1, 2],
        [4, 5]]),
 array([[ 3, 66],
        [ 6, 67]])]

In [106]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# Trigonometric functions
print("Sine:", np.sin(arr1))

# Exponential and logarithmic functions
print("Exponential:", np.exp(arr1))
print("Logarithm:", np.log(arr1))

# Aggregate functions
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Standard deviation:", np.std(arr1))


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Sine: [0.84147098 0.90929743 0.14112001]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Sum: 6
Mean: 2.0
Standard deviation: 0.816496580927726


In [107]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [108]:
np.mean(arr)

3.5

In [109]:
np.median(arr)

3.5

In [110]:
np.sum(arr1)

6

In [111]:
np.std(arr)

1.707825127659933

In [112]:
np.var(arr)

2.9166666666666665

In [113]:
arr = np.array([1, 2, 2, 3, 4])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Percentile:", np.percentile(arr, 50))
print("Unique elements:", np.unique(arr))


Mean: 2.4
Median: 2.0
Standard deviation: 1.019803902718557
Variance: 1.04
Minimum: 1
Maximum: 4
Percentile: 2.0
Unique elements: [1 2 3 4]


In [114]:
print("Random array:", np.random.rand(3))
print("Normal distribution:", np.random.normal(0, 1, 3))
print("Random choice:", np.random.choice([1, 2, 3, 4, 5], 3))


Random array: [0.26804538 0.41889729 0.49291614]
Normal distribution: [-0.83093897 -0.37069664 -1.01149806]
Random choice: [4 2 4]


In [118]:
np.random.rand(2,3)

array([[0.83401526, 0.0406547 , 0.02735449],
       [0.86574769, 0.3279173 , 0.88516262]])

In [119]:
arr = np.array([1, 2, 3, 4, 5])

# Basic slicing
print("First three elements:", arr[:3])

# Boolean indexing
print("Elements greater than 2:", arr[arr > 2])

# Fancy indexing
indices = [0, 2, 4]
print("Elements at indices 0, 2, 4:", arr[indices])


First three elements: [1 2 3]
Elements greater than 2: [3 4 5]
Elements at indices 0, 2, 4: [1 3 5]


In [120]:
arr[arr>2]

array([3, 4, 5])

In [122]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[0], [1], [2]])

print("Broadcasted addition:\n", arr1 + arr2)


Broadcasted addition:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [123]:
arr = np.array([1, 2, 3, 4, 5])

# Save to binary file
np.save('array.npy', arr)

# Load from binary file
loaded_array = np.load('array.npy')
print("Loaded array:", loaded_array)

# Save to text file
np.savetxt('array.txt', arr)

# Load from text file
loaded_text_array = np.loadtxt('array.txt')
print("Loaded text array:", loaded_text_array)


Loaded array: [1 2 3 4 5]
Loaded text array: [1. 2. 3. 4. 5.]


In [124]:
arr = np.array([1, 2, 3, 4, 5])

In [125]:
np.where(arr>3,arr,-1)

array([-1, -1, -1,  4,  5])

In [127]:

arr = np.array([1, 2, 2, 3, 4])
np.unique(arr)

array([1, 2, 3, 4])

In [128]:
arr = np.array([1, 2, 3, 4, 5])

# Where
print("Elements greater than 3:", np.where(arr > 3, arr, -1))

# Unique
arr = np.array([1, 2, 2, 3, 4])
print("Unique elements:", np.unique(arr))

# Meshgrid
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)

# Sort
arr = np.array([3, 1, 2])
print("Sorted array:", np.sort(arr))

# Searchsorted
print("Indices to insert to maintain order:", np.searchsorted(arr, 2))


Elements greater than 3: [-1 -1 -1  4  5]
Unique elements: [1 2 3 4]
Meshgrid X:
 [[1 2 3]
 [1 2 3]]
Meshgrid Y:
 [[4 4 4]
 [5 5 5]]
Sorted array: [1 2 3]
Indices to insert to maintain order: 2


In [129]:
arr = np.array([0, 1, 0, 0])
fft_result = np.fft.fft(arr)
print("FFT result:", fft_result)

ifft_result = np.fft.ifft(fft_result)
print("Inverse FFT result:", ifft_result)


FFT result: [ 1.+0.j  0.-1.j -1.+0.j  0.+1.j]
Inverse FFT result: [0.+0.j 1.+0.j 0.+0.j 0.+0.j]


In [130]:
matrix = np.array([[1, 2], [3, 4]])

# Determinant
print("Determinant:", np.linalg.det(matrix))

# Inverse
print("Inverse:\n", np.linalg.inv(matrix))

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [131]:
arr = np.array([1, 2, 3, 4, -1])
masked_arr = np.ma.masked_less(arr, 0)
print("Masked array:", masked_arr)


Masked array: [1 2 3 4 --]


In [132]:
# Random sampling
print("Random float:", np.random.random())
print("Random integer:", np.random.randint(0, 10))
print("Random choice:", np.random.choice([1, 2, 3, 4, 5]))


Random float: 0.7516959065581287
Random integer: 9
Random choice: 3


In [133]:
import numpy as np

# Vectors
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

# Dot Product
dot_product = np.dot(vec1, vec2)
print("Dot Product:", dot_product)

# Matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix Multiplication
matrix_product = np.matmul(matrix1, matrix2)
print("Matrix Multiplication:\n", matrix_product)

# Inner and Outer Product
inner_product = np.inner(vec1, vec2)
print("Inner Product:", inner_product)

outer_product = np.outer(vec1, vec2)
print("Outer Product:\n", outer_product)

# Matrix Determinant
determinant = np.linalg.det(matrix1)
print("Determinant:", determinant)

# Matrix Inverse
inverse_matrix = np.linalg.inv(matrix1)
print("Inverse Matrix:\n", inverse_matrix)

# Solving Linear Equations
# Coefficient matrix
A = np.array([[3, 1], [1, 2]])
# Constant terms
b = np.array([9, 8])
# Solve for x in Ax = b
solution = np.linalg.solve(A, b)
print("Solution to the linear equations:", solution)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Matrix Norm
norm = np.linalg.norm(matrix1)
print("Matrix Norm:", norm)

# Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(matrix1)
print("U matrix:\n", U)
print("Singular values:", S)
print("V matrix:\n", V)


Dot Product: 32
Matrix Multiplication:
 [[19 22]
 [43 50]]
Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Determinant: -2.0000000000000004
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Solution to the linear equations: [2. 3.]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Matrix Norm: 5.477225575051661
U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
